language: python
sudo: false
addons:
  apt:
    packages:
    - python-lxml
  firefox: "59.0.2"
python:
  - "2.7"
  - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install robotframework
  - pip install decorator docutils setuptools
  - pip install selenium robotframework-selenium2library
  - pip install requests robotframework-requests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "pybot --version ; uname -a"
  - "firefox --version"
  - "pybot test/exercise00*.robot"
env:
  matrix:
  - BROWSER=firefox
