language: python
sudo: false
addons:
  apt:
    packages:
    - python-lxml
python:
  - "2.6"
  - "2.7"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.16.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install robotframework
  - pip install decorator docutils setuptools
  - pip install selenium robotframework-selenium2library
  - pip install requests robotframework-requests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "pybot --version ; uname -a"
  - "firefox --version"
  - "pybot test/exercise00*.robot"
env:
  matrix:
  - BROWSER=firefox
