language: python
sudo: false
addons:
  apt:
    packages:
    - python-lxml
    - libxml2-devel 
    - libxslt-devel
python:
  - "2.6"
  - "2.7"
install:
  - pip install robotframework
  - pip install decorator docutils setuptools
  - pip install selenium robotframework-selenium2library
  - pip install requests robotframework-requests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "pybot --version ; uname -a"
  - "firefox --version"
  - "pybot test/exercise00*.robot"
env:
  matrix:
  - BROWSER=firefox
