language: python
sudo: false
python:
  - "2.6"
  - "2.7"
install:
  - pip install robotframework
  - pip install decorator docutils setuptools
  - pip install selenium robotframework-selenium2library
  - pip install requests robotframework-requests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "firefox --version"
  - "pybot test/exercise001.robot"
env:
  matrix:
  - BROWSER=firefox
